config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import home

urlpatterns = [
    path("mailmanager/", include("mailmanager.urls", namespace="mailmanager")),
    path('admin/', admin.site.urls),
    path('tracker', include('tracker.urls', namespace='tracker')),
    path("user/", include("user.urls", namespace="user")),
    path("campain/", include("emailservice.urls", namespace="campain")),
    path("", home, name="home"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emailservice/urls.py
from django.urls import path
from . import views

app_name = 'campain'

urlpatterns = [
    path('create', view=views.CreateNewCampain.as_view(),
         name='create'),
    path('list', view=views.EmailList.as_view(),name='list'),
    # Add more paths here
    path('detail/<int:pk>', view=views.EmailDetail.as_view(),name='detail'),
    path('update/<int:pk>', view=views.EmailUpdate.as_view(),name='update'),
    path('delete/<int:pk>', view=views.EmailDelete.as_view(),name='delete'),
]

user/urls.py
from django.urls import path
from .views import CustomLoginView, SignUpView, home, UserProfileView

app_name = 'user'

urlpatterns = [
    path("login", CustomLoginView.as_view(), name="login"),
    path("register", SignUpView.as_view(), name="register"),
    path("home", home, name="home"),
    path("profile", UserProfileView.as_view(), name="profile")
]

templates/utils/form.html
<form method="post" class="row g-3 needs-validation" novalidate>
    {% csrf_token %}

    <!-- Loop through all form fields dynamically -->
    {% for field in form %}
    <div class="col-12">
        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
        <div class="input-group has-validation">
            {{ field }}
            <div class="invalid-feedback">{{ field.errors }}</div>
        </div>
    </div>
    {% endfor %}

    {% if form.non_field_errors %}
    <div class="col-12">
        <div class="alert alert-danger">{{ form.non_field_errors }}</div>
    </div>
    {% endif %}

    {% if submit_label == "Register" %}
    <div class="col-12 ">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="terms" required>
            <label class="form-check-label" for="terms">
                I agree to the <a href="#">terms and conditions</a>
            </label>
            <div class="invalid-feedback">
                You must agree before submitting.
            </div>
        </div>
    </div>
    {% endif %}

    <div class="col-12">
        <button class="btn btn-primary w-100" type="submit">{{ submit_label }}</button>
    </div>
</form>

templates/utils/sidebar.html
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link " href="{% url 'home' %}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'campain:list' %}">
                <i class="bi bi-envelope-paper-heart-fill"></i>
                <span>Campaign</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="#">
                <i class="bi bi-card-list"></i>
                <span>Email List</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-bar-chart"></i><span>Charts</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="charts-chartjs.html">
                        <i class="bi bi-circle"></i><span>Chart.js</span>
                    </a>
                </li>
                <li>
                    <a href="charts-apexcharts.html">
                        <i class="bi bi-circle"></i><span>ApexCharts</span>
                    </a>
                </li>
                <li>
                    <a href="charts-echarts.html">
                        <i class="bi bi-circle"></i><span>ECharts</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Charts Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-gem"></i><span>Icons</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="icons-bootstrap.html">
                        <i class="bi bi-circle"></i><span>Bootstrap Icons</span>
                    </a>
                </li>
                <li>
                    <a href="icons-remix.html">
                        <i class="bi bi-circle"></i><span>Remix Icons</span>
                    </a>
                </li>
                <li>
                    <a href="icons-boxicons.html">
                        <i class="bi bi-circle"></i><span>Boxicons</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Icons Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'user:profile' %}">
                <i class="bi bi-person"></i>
                <span>Profile</span>
            </a>
        </li><!-- End Profile Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>F.A.Q</span>
            </a>
        </li><!-- End F.A.Q Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="pages-contact.html">
                <i class="bi bi-envelope"></i>
                <span>Contact</span>
            </a>
        </li><!-- End Contact Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="pages-register.html">
                <i class="bi bi-card-list"></i>
                <span>Register</span>
            </a>
        </li><!-- End Register Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'user:login' %}">
                <i class="bi bi-box-arrow-in-right"></i>
                <span>Login</span>
            </a>
        </li><!-- End Login Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="pages-error-404.html">
                <i class="bi bi-dash-circle"></i>
                <span>Error 404</span>
            </a>
        </li><!-- End Error 404 Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="pages-blank.html">
                <i class="bi bi-file-earmark"></i>
                <span>Blank</span>
            </a>
        </li><!-- End Blank Page Nav -->

    </ul>

</aside><!-- End Sidebar-->