config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.views import home

urlpatterns = [
    path("mailmanager/", include("mailmanager.urls", namespace="mailmanager")),
    path('admin/', admin.site.urls),
    path('tracker', include('tracker.urls', namespace='tracker')),
    path("user/", include("user.urls", namespace="user")),
    path("campain/", include("emailservice.urls", namespace="campain")),
    path("", home, name="home"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emailservice/urls.py
from django.urls import path
from . import views

app_name = 'campain'

urlpatterns = [
    path('create', view=views.CreateNewCampain.as_view(),
         name='create'),
    path('list', view=views.EmailList.as_view(),name='list'),
    # Add more paths here
    path('detail/<int:pk>', view=views.EmailDetail.as_view(),name='detail'),
    path('update/<int:pk>', view=views.EmailUpdate.as_view(),name='update'),
    path('delete/<int:pk>', view=views.EmailDelete.as_view(),name='delete'),
]

user/urls.py
from django.urls import path
from .views import CustomLoginView, SignUpView, home, UserProfileView

app_name = 'user'

urlpatterns = [
    path("login", CustomLoginView.as_view(), name="login"),
    path("register", SignUpView.as_view(), name="register"),
    path("home", home, name="home"),
    path("profile", UserProfileView.as_view(), name="profile")
]

emailservice/models.py
from django.db import models
from django.db.utils import IntegrityError

# Create your models here.
from tracker.models import EmailOpen
from django.urls import reverse
import uuid
from ckeditor.fields import RichTextField


class EmailCampaign(models.Model):
    name = models.CharField(max_length=255)
    tracking_id = models.UUIDField(
        default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.CharField(max_length=255)
    body = RichTextField()
    number_of_opens = models.IntegerField(default=0)
    email_list = models.ForeignKey(
        'EmailList', on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    camping_email = models.OneToOneField('mailmanager.EmailSetting', blank=True, related_name='camping_email',on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def increase_opens(self, ip_address, user_agent="Unknown", city="Unknown", region="Unkown", country="Unkown", isp="Unknown"):
        try:
            EmailOpen.objects.create(
                tracking_id=self,
                ip_address=ip_address,
                user_agent=user_agent,
                city=city,
                region=region,
                country=country,
                isp=isp,
            )
            self.number_of_opens += 1
            self.save()
        except IntegrityError:
            pass

    def get_absolute_url(self):
        return reverse('tracker:track_email_open', kwargs={'tracking_id': self.tracking_id})

    def create_tracker(self):
        self.body += f'<img src="{self.get_absolute_url()}" alt="Email Open Tracker" width="1" height="1" style="display:none;">'
        self.save()

    def save(self, *args, **kwargs):
        obj = super().save(*args, **kwargs)
        if not self.body.__contains__(self.get_absolute_url()):
            self.create_tracker()
        return obj


class EmailList(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='email_lists/',
                            default='profile_pics/default.jpg')
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

emailservice/forms.py
from django.forms import ModelForm
from .models import EmailCampaign
from django import forms
from emailservice.models import EmailList
from mailmanager.models import EmailSetting



class EmailCampaignForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Campaign Name',
        'id': 'name'
    }))
    subject = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email Subject',
        'id': 'subject'
    }))
    email_list = forms.ModelChoiceField(queryset=EmailList.objects.all(), widget=forms.Select(attrs={
        'class': 'form-control',
        'id': 'email_list'
    }))

    camping_email = forms.ModelChoiceField(queryset=EmailSetting.objects.all(), widget=forms.Select(attrs={
        'class': 'form-control',
        'id': 'camping_email'
    }))

    class Meta:
        model = EmailCampaign
        fields = ['name', 'subject', 'body', 'email_list', 'camping_email']
        labels = {
            'name': 'Campaign Name',
            'subject': 'Email Subject',
            'body': 'Email Body',
            'email_list': 'Email List',
            'camping_email': 'Campine Email'
        }
        help_texts = {
            'name': 'Enter a name for the campaign',
            'subject': 'Enter the subject of the email',
            'body': 'Enter the body of the email',
            'email_list': 'Select the email list to send the email to',
            'camping_email': 'Select the email to send the Email From'
        }
        error_messages = {
            'name': {
                'required': 'Please enter a name for the campaign'
            },
            'subject': {
                'required': 'Please enter the subject of the email'
            },
            'body': {
                'required': 'Please enter the body of the email'
            },
            'email_list': {
                'required': 'Please select an email list'
            },
            'camping_email': {
                'required': 'Please select an email to send the email from'
            }
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['camping_email'].queryset = EmailSetting.objects.filter(user=user)


class CampaignDeleteForm(forms.Form):
    campine_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Campaign Name',
        'id': 'campine_name'
    }))

    def __init__(self, campaign, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.campaign = campaign

    def clean_campine_name(self):
        campine_name = self.cleaned_data['campine_name']
        print(campine_name)
        print(self.campaign.name)
        if campine_name != self.campaign.name:
            raise forms.ValidationError(f'"{campine_name}", The campaign name does not match')
        return campine_name

emailservice/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import EmailCampaign
from user.models import User
from .forms import EmailCampaignForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CampaignDeleteForm

# Create your views here.
class CustomLoginRequiredMixin(LoginRequiredMixin):
    def get_login_url(self):
        return reverse_lazy('user:login')





class CreateNewCampain(CustomLoginRequiredMixin,CreateView):
    template_name = 'emailservice/new_campain.html'
    form_class = EmailCampaignForm
    success_url = reverse_lazy('campain:email_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Pass the user to the form
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class EmailList(CustomLoginRequiredMixin, ListView):
    model = EmailCampaign
    template_name = 'emailservice/email_list.html'
    context_object_name = 'email_campaigns'
    ordering = ['-created_at']  # Proper way to apply sorting

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the fields to the template
        context['fields'] = ["name", "subject", "number_of_opens", "email_list"]
        return context




class EmailDetail(CustomLoginRequiredMixin, DetailView):
    model = EmailCampaign
    template_name = 'emailservice/email_detail.html'
    context_object_name = 'email_campaign'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the fields to the template
        context['fields'] = ["name", "subject", "number_of_opens", "email_list"]
        return context

class EmailUpdate(CustomLoginRequiredMixin, UpdateView):
    model = EmailCampaign
    template_name = 'emailservice/update_campain.html'
    form_class = EmailCampaignForm

    def get_success_url(self):
        return reverse_lazy('campain:update', kwargs={'pk': self.object.pk})


    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Pass the user to the form
        return kwargs


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Dummy data for email opens and regions
        total_email_opens = 150  # Example: Total email opens
        top_regions = [
            ("New York", 40),   # Region with number of opens
            ("London", 35),
            ("Tokyo", 30),
            ("Delhi", 25),
            ("Berlin", 20)
        ]
        top_times = [
            ("10:00 AM", 50),   # Time with number of opens
            ("2:00 PM", 40),
            ("5:00 PM", 30)
        ]
        least_active_time = "12:00 PM"   # Example: Least active time
        least_active_time_count = 5      # Example: Number of opens at that time

        # Pass the dummy data into the context
        context["campain_key"] = self.kwargs["pk"]
        context['total_email_opens'] = total_email_opens
        context['top_regions'] = top_regions
        context['top_times'] = top_times
        context['least_active_time'] = least_active_time
        context['least_active_time_count'] = least_active_time_count

        return context





class EmailDelete(CustomLoginRequiredMixin, DeleteView):
    model = EmailCampaign
    template_name = 'emailservice/delete_campain.html'
    success_url = reverse_lazy('campain:list')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CampaignDeleteForm(campaign=self.object)
        return self.render_to_response(self.get_context_data(form=form))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CampaignDeleteForm(self.object, request.POST)

        if form.is_valid():
            return self.delete(request, *args, **kwargs)
        else:
            return self.render_to_response(self.get_context_data(form=form))


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["campain_name"] = self.object.name
        return context

templates/emailservice/delete_campain.html
{% extends 'base.html' %}

{% block title %}Confirm Delete Email Campaign{% endblock title %}

{% block content %}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Delete Email Campaign</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'user:home' %}">Home</a></li>
                <li class="breadcrumb-item">Email Campaigns</li>
                <li class="breadcrumb-item active">Confirm Delete</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Are you sure you want to delete this email campaign?</h5>
                        <p>
                            Campaign Name: <strong>{{ object.name }}</strong><br>
                            Email Subject: {{ object.subject }}
                        </p>

                        <!-- Form to confirm deletion -->
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.campine_name }}
                            <p><small>To Delete this Campine Please Write "<strong> {{ campain_name }} </strong>"</small></p>
                            <button type="submit" class="btn btn-danger">Confirm Delete</button>
                            <a href="{% url 'campain:update' object.pk %}" class="btn btn-secondary">Cancel</a>
                        </form>

                        <!-- Error message if the name does not match -->
                        {% if form.errors %}
                        <div class="alert alert-danger mt-3">
                            {{ form.campine_name.errors }}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

</main><!-- End #main -->
{% endblock content %}

templates/emailservice/email_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load static %}

{% block title %}Email List{% endblock %}
{% block content %}

{% include 'utils/sidebar.html' %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>Email Campaign List</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'user:home' %}">Home</a></li>
          <li class="breadcrumb-item">Email Campaigns</li>
          <li class="breadcrumb-item active">List</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Email Campaigns</h5>

              <!-- Dynamic table with headers and data -->
              <table class="table datatable">
                <thead>
                  <tr>
                    {% for field in fields %}
                      <th>{{ field|title }}</th> <!-- Dynamic header names with capitalized titles -->
                    {% endfor %}
                  </tr>
                </thead>
                <tbody>
                  {% for campaign in email_campaigns %}
                  <tr>
                    {% for field in fields %}
                      {% if field == 'name' %}
                        <td>
                          <a href="{% url 'campain:update' campaign.pk %}">
                            {{ campaign|get_field_value:field }}
                          </a>
                        </td> <!-- Link to edit page if the field is 'email' -->
                      {% else %}
                        <td>{{ campaign|get_field_value:field }}</td> <!-- Dynamic data rendering -->
                      {% endif %}
                    {% endfor %}
                  </tr>
                  {% empty %}
                  <tr>
                    <td colspan="{{ fields|length }}">No campaigns available</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              <!-- End dynamic table -->

            </div>
          </div>

        </div>
      </div>
    </section>

</main><!-- End #main -->

{% endblock content %}

templates/emailservice/new_campain.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Email Campaign{% endblock title %}


{% block content %}

{% include 'utils/sidebar.html' %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>Email Campaign Form</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Forms</li>
          <li class="breadcrumb-item active">Email Campaign</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <!-- Left side: Campaign Name, Subject, Email List -->
        <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Campaign Details</h5>

              {{ form.media }}

              <!-- Form Fields on the Left -->
              <form method="POST" action="{% url 'campain:create' %}">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="name" class="form-label">Campaign Name</label>
                  {{ form.name }}
                </div>
                <div class="mb-3">
                  <label for="subject" class="form-label">Email Subject</label>
                  {{ form.subject }}
                </div>
                <div class="mb-3">
                  <label for="email_list" class="form-label">Email List</label>
                  {{ form.email_list }}
                </div>
                <div class="mb-3">
                    <label for="email_list" class="form-label">Campining Email</label>
                    {{ form.camping_email }}
                  </div>
            </div>
          </div>
        </div>

        <!-- Right side: CKEditor -->
        <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Email Body</h5>

              <!-- CKEditor for Email Body -->
              <div class="mb-3">
                <label for="body" class="form-label">Compose Email</label>
                {{ form.body }}
              </div>

              <button type="submit" class="btn btn-primary">Submit</button>
              </form><!-- End Form -->
            </div>
          </div>
        </div>

      </div>
    </section>

</main><!-- End #main -->
{% endblock content %}

templates/emailservice/update_campain.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Update Campaign{% endblock title %}

{% block content %}

{% include 'utils/sidebar.html' %}

<main id="main" class="main">

    <div class="container">
        <div class="row">
          <!-- Left Column (Form Section) -->
          <div class="col-lg-8 mb-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Campaign Details</h5>

                {{ form.media }}

                <!-- Form Fields for Campaign Name, Subject, Email List -->
                <form method="POST">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label for="name" class="form-label">Campaign Name</label>
                    {{ form.name }}
                  </div>
                  <div class="mb-3">
                    <label for="subject" class="form-label">Email Subject</label>
                    {{ form.subject }}
                  </div>
                  <div class="mb-3">
                    <label for="email_list" class="form-label">Email List</label>
                    {{ form.email_list }}
                  </div>
                  <div class="mb-3">
                    <label for="email_list" class="form-label">Campining Email</label>
                    {{ form.camping_email }}
                  </div>

                  <!-- CKEditor Section for Email Body -->
                  <div class="mb-3">
                    <label for="email_body" class="form-label">Email Body</label>
                    {{ form.body }}  <!-- Assuming form.body is the CKEditor field -->
                  </div>

                  <!-- Submit Button for Update -->
                  <button type="submit" class="btn btn-success">Update</button>
                </form>
              </div>
            </div>
          </div>

          <!-- Right Column (Email Stats Section) for larger screens -->
          <div class="col-lg-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Campaign Stats</h5>

                <!-- Display number of email opens -->
                <div class="mb-3">
                  <strong>Total Email Opens:</strong> {{ total_email_opens }}
                </div>

                <!-- Display top 5 regions where emails were opened -->
                <div class="mb-3">
                  <strong>Top 5 Regions:</strong>
                  <ul>
                    {% for region, count in top_regions %}
                      <li>{{ region }}: {{ count }} opens</li>
                    {% endfor %}
                  </ul>
                </div>

                <!-- Display peak email open times -->
                <div class="mb-3">
                  <strong>Top Times When Emails Were Opened:</strong>
                  <ul>
                    {% for time, count in top_times %}
                      <li>{{ time }}: {{ count }} opens</li>
                    {% endfor %}
                  </ul>
                </div>

                <!-- Display least active times -->
                <div class="mb-3">
                  <strong>Least Active Time:</strong> {{ least_active_time }} ({{ least_active_time_count }} opens)
                </div>
              </div>
            </div>

            <!-- Delete Button -->
            <a href="{% url 'campain:list' %}" class="btn btn-secondary">Cancel</a>
            <a href="{% url 'campain:delete' campain_key %}" class="btn btn-danger">Delete</a>

          </div>
        </div>
      </div>

</main><!-- End #main -->

{% endblock content %}